from python:3.8-alpine
ENV PATH="/scripts:${PATH}"
ENV PATH="/home/user/.local/bin:${PATH}"
#COPY /req_uwsgi.txt ./requirements.txt
#RUN apk add --update --no-cache --virtual .tmp gcc  libc-dev linux-headers
#RUN pip install -r /requirements.txt
#RUN apk del .tmp
RUN pip install gunicorn
RUN mkdir /app
COPY /uwsgi /uwsgi
COPY /app /app
WORKDIR /app
COPY ./scripts /scripts 
RUN chmod +x /scripts/*
RUN mkdir -p /vol/web/media
RUN mkdir -p /vol/web/static
RUN adduser -D user 
RUN chown -R user:user /vol
RUN chmod -R 755 /vol/web
USER user 
#ENTRYPOINT ["/usr/local/bin/python", "/scripts/print.py"]
#ENTRYPOINT which python
#CMD python /scripts2/py2.py
CMD gunicorn -w 4 myapp:app

#CMD python x.py

# CMD uwsgi --http :9090 --wsgi-file /uwsgi/foobar.py
